version: "3.9"

services:
    db:
        image: mysql:8
        volumes:
            - sdi-mysql-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: scouting
        ports:
            - 4099:3306
            
    scouting-data-ingest:
        build: .
        command: [sh, -c, "python -m main --refresh-time 600 & (sleep 10s && python -m DataDashboard)"]
        stdin_open: true
        ports:
            - 5000:5000
            - 5001:5001
        working_dir: /code
        volumes:
            - ./src/:/code
        environment:
            MYSQL_HOST: scouting-data-ingest-week4.ccjho2z8otts.us-east-2.rds.amazonaws.com
            #MYSQL_HOST: db
            MYSQL_USER: admin
            MYSQL_PASSWORD: competition1
            # Replace [Key] in the following line with your TBA Key
            TBA_KEY: oPvuWtX7QgdpPQmfKavrKeqjcgpxV4A0ayVe543hOaM9VFinQIcJzdQmX9OvYwuV
            SIM_URL: http://127.0.0.1:5000
            YEAR: 2022
            # Replace [File Name] in the following line with your Google Credentials File Name
            G_CRED: our-audio-273419-34a1bb6bb461.json
            G_SHEET: Scouting Data Collection (Responses)
            # Replace [Name] in the following line with your name
            SIM_SHEET: Scouting Data Collection (Responses) - Kandasamy Chokkalingam
            EVENT: dc319
        depends_on:
            - db


volumes:
    sdi-mysql-data:
