version: "3.9"

services:
    db:
        image: mysql:8
        volumes:
            - sdi-mysql-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: scouting
        ports:
            - 4099:3306
            
    scouting-data-ingest:
        build: .
        stdin_open: true
        ports:
            - 5000:5000
        working_dir: /code
        volumes:
            - ./src/:/code
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            TBA_KEY: 4cV0gYJGDaQnsLy2i8GGX4sllZ0KR6bjJaEHepZUMCuSQymX5PY8vHZeVePRpuyz
            SIM_URL: http://127.0.0.1:5000
            YEAR: 2020
            G_CRED: our-audio-273419-34a1bb6bb461.json
            G_SHEET: Scouting Data Collection (Responses)
            SIM_SHEET: Scouting Data Collection (Responses) - Kandasamy Chokkalingam
            EVENT: vahay 
        depends_on:
            - db
volumes:
    sdi-mysql-data:
